### ISSUE TITLE
Urrrrm

### ISSUE THREAD

**Issue by JohnLoveDA** [StylianosPolychroniadis/NthDimension#2]
I've been trying to compile this source on and off for the past 6 months... however, I can't get past the compile errors that suggest that multiple objects are missing from the NthDimension/data/models/ directory.  I simply wanted to check out what you've achieved.

**Comment by polytronicgr** [comment]
Indeed the base models were missing. You should be able to enter the engine loaded-state properly now. Keep in mind that no scene assets have been uploaded to the repository yet so you won't be able to load any scenes. You need to provide your own assets atm. You also need a scene definition file (.xsn) that must be located under C:\Users\\[Username]\Documents\NthDimension\Cache folder. I shall upload the Scene Definition File document describing the format (it's a plain XML file) soon. Thanks for the heads up!
